//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace homework0927.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class StockEntities : DbContext
    {
        public StockEntities()
            : base("name=StockEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<OrderDetail> OrderDetails { get; set; }
        public virtual DbSet<PostInfo> PostInfoes { get; set; }
        public virtual DbSet<ProdInfo> ProdInfoes { get; set; }
        public virtual DbSet<CustLogin> CustLogins { get; set; }
        public virtual DbSet<OrderInfo> OrderInfoes { get; set; }
        public virtual DbSet<VW_OrderAndDetail> VW_OrderAndDetail { get; set; }
        public virtual DbSet<VW_OrderAndDetailAndCust> VW_OrderAndDetailAndCust { get; set; }
        public virtual DbSet<CustomerInfo> CustomerInfoes { get; set; }
        public virtual DbSet<PostCInfo> PostCInfoes { get; set; }
        public virtual DbSet<VW_MyOrder> VW_MyOrder { get; set; }
    }
}
