//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace homework0927.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_OrderAndDetailAndCust
    {
        public string PostName { get; set; }
        public int PostCategory { get; set; }
        public string ProdName { get; set; }
        public int OrderId { get; set; }
        public Nullable<int> OrderTotal { get; set; }
        public Nullable<System.DateTime> OrderTime { get; set; }
        public int ProdPrice { get; set; }
        public int ProdQuantity { get; set; }
        public string CustName { get; set; }
        public string CustRoad { get; set; }
        public string CustCellPhone { get; set; }
        public int id { get; set; }
        public int CustId { get; set; }
        public string CityName { get; set; }
    }
}
