//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace homework0927.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductCommet
    {
        public int Id { get; set; }
        public string CustId { get; set; }
        public string Content { get; set; }
        public System.DateTime CreateDate { get; set; }
        public int ProdId { get; set; }
    }
}
